class Paint{
  final int id;
  final String name;
  final String hex;
  final bool metallic;
  final int typeId;
  final int colourId;
  final int accountId;

  Paint({required this.id, required this.name, required this.hex, required this.metallic, required this.typeId, required this.colourId, required this.accountId});
}

final List<Paint> citadelPaintList = <Paint>[
  Paint(id: 1, name: "Abaddon Black", hex: "0xFF231F20", metallic: false, typeId: 1, colourId: 1, accountId: 1),
  Paint(id: 2, name: "Administratum Grey", hex: "0xFF949B94", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 3, name: "Agrax Earthshade", hex: "0xFF5A543C", metallic: false, typeId: 6, colourId: 3, accountId: 1),
  Paint(id: 4, name: "Agrellan Badland", hex: "0xFFA17359", metallic: false, typeId: 8, colourId: 3, accountId: 1),
  Paint(id: 5, name: "Agrellan Earth", hex: "0xFF92816D", metallic: false, typeId: 8, colourId: 3, accountId: 1),
  Paint(id: 6, name: "Ahriman Blue", hex: "0xFF00A5B9", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 7, name: "Alaitoc Blue", hex: "0xFF295788", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 8, name: "Altdorf Guard Blue", hex: "0xFF1F56A8", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 9, name: "Armageddon Dust", hex: "0xFFCBAD0D", metallic: false, typeId: 8, colourId: 15, accountId: 1),
  Paint(id: 10, name: "Astorath Red", hex: "0xFF962F28", metallic: false, typeId: 3, colourId: 12, accountId: 1),
  Paint(id: 11, name: "Astrogranite", hex: "0xFF787878", metallic: false, typeId: 8, colourId: 7, accountId: 1),
  Paint(id: 12, name: "Athonian Camoshade", hex: "0xFF798C3D", metallic: false, typeId: 6, colourId: 6, accountId: 1),
  Paint(id: 13, name: "Auric Armour Gold", hex: "0xFFE9C278", metallic: true, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 14, name: "Averland Sunset", hex: "0xFFFCB825", metallic: false, typeId: 1, colourId: 15, accountId: 1),
  Paint(id: 15, name: "Baharroth Blue", hex: "0xFF78C4C7", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 16, name: "Balor Brown", hex: "0xFF8B5910", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 17, name: "Balthasar Gold", hex: "0xFF87542F", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 18, name: "Baneblade Brown", hex: "0xFF927F6E", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 19, name: "Bestigor Flesh", hex: "0xFFD28B57", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 20, name: "Biel-Tan Green", hex: "0xFF479259", metallic: false, typeId: 6, colourId: 6, accountId: 1),
  Paint(id: 21, name: "Blood for the Blood God", hex: "0xFF581011", metallic: false, typeId: 8, colourId: 12, accountId: 1),
  Paint(id: 22, name: "Blue Horror", hex: "0xFFA2BAD2", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 23, name: "Brass Scorpion", hex: "0xFFB7895F", metallic: true, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 24, name: "Bugman's Glow", hex: "0xFF845045", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 25, name: "Cadian Fleshtone", hex: "0xFFC87958", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 26, name: "Caledor Sky", hex: "0xFF396F9E", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 27, name: "Calgar Blue", hex: "0xFF4273B8", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 28, name: "Caliban Green", hex: "0xFF00401E", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 29, name: "Carroburg Crimson", hex: "0xFF9A4073", metallic: false, typeId: 6, colourId: 10, accountId: 1),
  Paint(id: 30, name: "Casandora Yellow", hex: "0xFFF1CB4E", metallic: false, typeId: 6, colourId: 15, accountId: 1),
  Paint(id: 31, name: "Castellan Green", hex: "0xFF304921", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 32, name: "Celestra Grey", hex: "0xFF90A8A8", metallic: false, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 33, name: "Chaos Black", hex: "0xFF000000", metallic: false, typeId: 7, colourId: 1, accountId: 1),
  Paint(id: 34, name: "Coelia Greenshade", hex: "0xFF4A7F79", metallic: false, typeId: 6, colourId: 6, accountId: 1),
  Paint(id: 35, name: "Corax White", hex: "0xFFFFFFFF", metallic: false, typeId: 1, colourId: 14, accountId: 1),
  Paint(id: 36, name: "Daemonette Hide", hex: "0xFF696685", metallic: false, typeId: 1, colourId: 11, accountId: 1),
  Paint(id: 37, name: "Dark Reaper", hex: "0xFF3C5051", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 38, name: "Dawnstone", hex: "0xFF70756E", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 39, name: "Death Guard Green", hex: "0xFF9C9171", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 40, name: "Deathclaw Brown", hex: "0xFFB36853", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 41, name: "Deathworld Forest", hex: "0xFF5D6732", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 42, name: "Dechala Lilac", hex: "0xFFB59ECC", metallic: false, typeId: 4, colourId: 11, accountId: 1),
  Paint(id: 43, name: "Deepkin Flesh", hex: "0xFFD2D4C7", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 44, name: "Doombull Brown", hex: "0xFF5D000A", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 45, name: "Dorn Yellow", hex: "0xFFE3D28C", metallic: false, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 46, name: "Drakenhof Nightshade", hex: "0xFF3B5997", metallic: false, typeId: 6, colourId: 2, accountId: 1),
  Paint(id: 47, name: "Dryad Bark", hex: "0xFF34312C", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 48, name: "Druchii Violet", hex: "0xFF6A397B", metallic: false, typeId: 6, colourId: 11, accountId: 1),
  Paint(id: 49, name: "Eldar Flesh", hex: "0xFFEDC184", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 50, name: "Elysian Green", hex: "0xFF758E3A", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 51, name: "Emperor's Children", hex: "0xFFB94278", metallic: false, typeId: 4, colourId: 10, accountId: 1),
  Paint(id: 52, name: "Eshin Grey", hex: "0xFF4A4F53", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 53, name: "Etherium Blue", hex: "0xFFA1B9D1", metallic: false, typeId: 3, colourId: 2, accountId: 1),
  Paint(id: 54, name: "Evil Sunz Scarlet", hex: "0xFFC21920", metallic: false, typeId: 4, colourId: 12, accountId: 1),
  Paint(id: 55, name: "The Fang", hex: "0xFF436276", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 56, name: "Fenrisian Grey", hex: "0xFF709CB7", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 57, name: "Fire Dragon Bright", hex: "0xFFF58651", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 58, name: "Flash Gitz Yellow", hex: "0xFFFFF200", metallic: false, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 59, name: "Flayed One Flesh", hex: "0xFFCBB48B", metallic: false, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 60, name: "Fuegan Orange", hex: "0xFFAD6E38", metallic: false, typeId: 6, colourId: 8, accountId: 1),
  Paint(id: 61, name: "Fulgrim Pink", hex: "0xFFF4AFCC", metallic: false, typeId: 4, colourId: 10, accountId: 1),
  Paint(id: 62, name: "Fulgurite Copper", hex: "0xFFBA8F6D", metallic: true, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 63, name: "Gauss Blaster Green", hex: "0xFF84C2A9", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 64, name: "Gehenna's Gold", hex: "0xFFD49761", metallic: true, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 65, name: "Genestealer Purple", hex: "0xFF7761AA", metallic: false, typeId: 4, colourId: 11, accountId: 1),
  Paint(id: 66, name: "Golden Griffon", hex: "0xFFC6B791", metallic: false, typeId: 3, colourId: 15, accountId: 1),
  Paint(id: 67, name: "Golgfag Brown", hex: "0xFF8B5435", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 68, name: "Gorthor Brown", hex: "0xFF654641", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 69, name: "Hashut Copper", hex: "0xFFC69169", metallic: true, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 70, name: "Hexos Palesun", hex: "0xFFF1DCA3", metallic: false, typeId: 3, colourId: 15, accountId: 1),
  Paint(id: 71, name: "Hexwraith Flame", hex: "0xFF00AA5C", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 72, name: "Hoeth Blue", hex: "0xFF4C7FB4", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 73, name: "Imrik Blue", hex: "0xFF4F8DBE", metallic: false, typeId: 3, colourId: 2, accountId: 1),
  Paint(id: 74, name: "Incubi Darkness", hex: "0xFF0B4849", metallic: false, typeId: 1, colourId: 4, accountId: 1),
  Paint(id: 75, name: "Ironbreaker", hex: "0xFF94999D", metallic: true, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 76, name: "Jokaero Orange", hex: "0xFFEE3823", metallic: false, typeId: 1, colourId: 8, accountId: 1),
  Paint(id: 77, name: "Kabalite Green", hex: "0xFF028D66", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 78, name: "Kantor Blue", hex: "0xFF002051", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 79, name: "Karak Stone", hex: "0xFFBB9662", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 80, name: "Khorne Red", hex: "0xFF6A0002", metallic: false, typeId: 1, colourId: 12, accountId: 1),
  Paint(id: 81, name: "Kislev Flesh", hex: "0xFFD6A876", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 82, name: "Krieg Khaki", hex: "0xFFB7AD78", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 83, name: "Leadbelcher", hex: "0xFF475659", metallic: true, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 84, name: "Liberator Gold", hex: "0xFFD5C4AA", metallic: true, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 85, name: "Longbeard Grey", hex: "0xFFB4AEAE", metallic: false, typeId: 3, colourId: 7, accountId: 1),
  Paint(id: 86, name: "Loren Forest", hex: "0xFF51702D", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 87, name: "Lothern Blue", hex: "0xFF33A2CF", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 88, name: "Lucius Lilac", hex: "0xFFB69FCB", metallic: false, typeId: 3, colourId: 11, accountId: 1),
  Paint(id: 89, name: "Lugganath Orange", hex: "0xFFF89E86", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 90, name: "Macragge Blue", hex: "0xFF0D407F", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 91, name: "Martian Ironcrust", hex: "0xFFF5945D", metallic: false, typeId: 8, colourId: 8, accountId: 1),
  Paint(id: 92, name: "Martian Ironearth", hex: "0xFF935442", metallic: false, typeId: 8, colourId: 8, accountId: 1),
  Paint(id: 93, name: "Mechanicus Standard Grey", hex: "0xFF3D4B4E", metallic: false, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 94, name: "Mephiston Red", hex: "0xFF991115", metallic: false, typeId: 1, colourId: 12, accountId: 1),
  Paint(id: 95, name: "Moot Green", hex: "0xFF52B246", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 96, name: "Mournfang Brown", hex: "0xFF650A09", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 97, name: "Naggaroth Night", hex: "0xFF3E3355", metallic: false, typeId: 1, colourId: 11, accountId: 1),
  Paint(id: 98, name: "Necron Compound", hex: "0xFFB1B5B8", metallic: true, typeId: 3, colourId: 7, accountId: 1),
  Paint(id: 99, name: "Niblet Green", hex: "0xFF648B32", metallic: false, typeId: 3, colourId: 6, accountId: 1),
  Paint(id: 100, name: "Nihilakh Oxide", hex: "0xFF85B59D", metallic: false, typeId: 8, colourId: 6, accountId: 1),
  Paint(id: 101, name: "Nuln Oil", hex: "0xFF151203", metallic: false, typeId: 6, colourId: 7, accountId: 1),
  Paint(id: 102, name: "Nurgle's Rot", hex: "0xFF9D8C30", metallic: false, typeId: 8, colourId: 15, accountId: 1),
  Paint(id: 103, name: "Nurgling Green", hex: "0xFF849B63", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 104, name: "Ogryn Camo", hex: "0xFF9EA94B", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 105, name: "Pallid Wych Flesh", hex: "0xFFCDCEBE", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 106, name: "Pink Horror", hex: "0xFF91305D", metallic: false, typeId: 4, colourId: 10, accountId: 1),
  Paint(id: 107, name: "Praxeti White", hex: "0xFFFFFFFF", metallic: false, typeId: 3, colourId: 14, accountId: 1),
  Paint(id: 108, name: "Rakarth Flesh", hex: "0xFFA29E92", metallic: false, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 109, name: "Ratskin Flesh", hex: "0xFFAE6B4E", metallic: false, typeId: 1, colourId: 8, accountId: 1),
  Paint(id: 110, name: "Reikland Fleshshade", hex: "0xFFA34529", metallic: false, typeId: 6, colourId: 12, accountId: 1),
  Paint(id: 111, name: "Retributor Armour", hex: "0xFFCEAE65", metallic: true, typeId: 1, colourId: 15, accountId: 1),
  Paint(id: 112, name: "Rhinox Hide", hex: "0xFF493335", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 113, name: "Runefang Steel", hex: "0xFFC6CBD0", metallic: true, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 114, name: "Runelord Brass", hex: "0xFFBCAFA0", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 115, name: "Russ Grey", hex: "0xFF547588", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 116, name: "Ryza Rust", hex: "0xFFCE6426", metallic: false, typeId: 3, colourId: 8, accountId: 1),
  Paint(id: 117, name: "Screamer Pink", hex: "0xFF7C1645", metallic: false, typeId: 1, colourId: 10, accountId: 1),
  Paint(id: 118, name: "Screaming Bell", hex: "0xFFB3562B", metallic: false, typeId: 1, colourId: 8, accountId: 1),
  Paint(id: 119, name: "Screaming Skull", hex: "0xFFD4D3A3", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 120, name: "Seraphim Sepia", hex: "0xFFBF793E", metallic: false, typeId: 6, colourId: 8, accountId: 1),
  Paint(id: 121, name: "Sigmarite", hex: "0xFFDAC38D", metallic: true, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 122, name: "Skarsnik Green", hex: "0xFF5F936F", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 123, name: "Skavenblight Dinge", hex: "0xFF48413B", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 124, name: "Skink Blue", hex: "0xFF59C1CE", metallic: false, typeId: 3, colourId: 2, accountId: 1),
  Paint(id: 125, name: "Skrag Brown", hex: "0xFF904A0F", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 126, name: "Skullcrusher Brass", hex: "0xFFE9C58B", metallic: true, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 127, name: "Slaanesh Grey", hex: "0xFF8E8C97", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 128, name: "Sotek Green", hex: "0xFF0C6A74", metallic: false, typeId: 4, colourId: 4, accountId: 1),
  Paint(id: 129, name: "Soulstone Blue", hex: "0xFF294C86", metallic: false, typeId: 8, colourId: 2, accountId: 1),
  Paint(id: 130, name: "Spiritstone Red", hex: "0xFFFD5D3D", metallic: false, typeId: 8, colourId: 12, accountId: 1),
  Paint(id: 131, name: "Squig Orange", hex: "0xFFA94F44", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 132, name: "Steel Legion Drab", hex: "0xFF5F5134", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 133, name: "Stirland Mud", hex: "0xFF473300", metallic: false, typeId: 8, colourId: 3, accountId: 1),
  Paint(id: 134, name: "Stegadon Scale Green", hex: "0xFF074864", metallic: false, typeId: 1, colourId: 4, accountId: 1),
  Paint(id: 135, name: "Stormfang", hex: "0xFF7188AA", metallic: false, typeId: 3, colourId: 2, accountId: 1),
  Paint(id: 136, name: "Stormhost Silver", hex: "0xFFD1D2D4", metallic: true, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 137, name: "Stormvermin Fur", hex: "0xFF736C66", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 138, name: "Straken Green", hex: "0xFF628026", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 139, name: "Sybarite Green", hex: "0xFF30A66C", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 140, name: "Sycorax Bronze", hex: "0xFFCBB394", metallic: true, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 141, name: "Sylvaneth Bark", hex: "0xFF5A5140", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 142, name: "Tallarn Sand", hex: "0xFFA67610", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 143, name: "Tau Light Ochre", hex: "0xFFBF6E1D", metallic: false, typeId: 8, colourId: 8, accountId: 1),
  Paint(id: 144, name: "Teclis Blue", hex: "0xFF317FC1", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 145, name: "Temple Guard Blue", hex: "0xFF329B8D", metallic: false, typeId: 4, colourId: 2, accountId: 1),
  Paint(id: 146, name: "Terminatus Stone", hex: "0xFFBDAA9B", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 147, name: "Thousand Sons Blue", hex: "0xFF18ABCC", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 148, name: "Thunderhawk Blue", hex: "0xFF417175", metallic: false, typeId: 4, colourId: 4, accountId: 1),
  Paint(id: 149, name: "Troll Slayer Orange", hex: "0xFFF46C2E", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 150, name: "Tuskgor Fur", hex: "0xFF883736", metallic: false, typeId: 4, colourId: 12, accountId: 1),
  Paint(id: 151, name: "Typhus Corrosion", hex: "0xFF453F31", metallic: false, typeId: 8, colourId: 3, accountId: 1),
  Paint(id: 152, name: "Tyrant Skull", hex: "0xFFC6AF8B", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 153, name: "Ulthuan Grey", hex: "0xFFC7E0DA", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 154, name: "Underhive Ash", hex: "0xFFBFBD80", metallic: false, typeId: 3, colourId: 3, accountId: 1),
  Paint(id: 155, name: "Ungor Flesh", hex: "0xFFD7A767", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 156, name: "Ushabti Bone", hex: "0xFFBCBC80", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 157, name: "Valhallan Blizzard", hex: "0xFFFDF9EE", metallic: false, typeId: 8, colourId: 14, accountId: 1),
  Paint(id: 158, name: "Waaagh! Flesh", hex: "0xFF20552B", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 159, name: "Warboss Green", hex: "0xFF3E7F5D", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 160, name: "Warpfiend Grey", hex: "0xFF6C6A75", metallic: false, typeId: 4, colourId: 7, accountId: 1),
  Paint(id: 161, name: "Warplock Bronze", hex: "0xFF695154", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 162, name: "Warpstone Glow", hex: "0xFF1E7332", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 163, name: "Waystone Green", hex: "0xFF018675", metallic: false, typeId: 8, colourId: 6, accountId: 1),
  Paint(id: 164, name: "Wazdakka Red", hex: "0xFF8C0A0C", metallic: false, typeId: 4, colourId: 12, accountId: 1),
  Paint(id: 165, name: "White Scar", hex: "0xFFFFFFFF", metallic: false, typeId: 4, colourId: 14, accountId: 1),
  Paint(id: 166, name: "Wild Rider Red", hex: "0xFFEB2E28", metallic: false, typeId: 4, colourId: 12, accountId: 1),
  Paint(id: 167, name: "Wrack White", hex: "0xFFDEDAD9", metallic: false, typeId: 3, colourId: 7, accountId: 1),
  Paint(id: 168, name: "Xereus Purple", hex: "0xFF471F5E", metallic: false, typeId: 4, colourId: 11, accountId: 1),
  Paint(id: 169, name: "XV-88", hex: "0xFF72481E", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 170, name: "Yriel Yellow", hex: "0xFFFFDB01", metallic: false, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 171, name: "Zamesi Desert", hex: "0xFFDCA026", metallic: false, typeId: 4, colourId: 8, accountId: 1),
  Paint(id: 172, name: "Zandri Dust", hex: "0xFF9E915C", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 173, name: "Aethermatic Blue", hex: "0xFF60A8C8", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 174, name: "Apothecary White", hex: "0xFFD8E0E0", metallic: false, typeId: 2, colourId: 14, accountId: 1),
  Paint(id: 175, name: "Asurmen Blue", hex: "0xFF0083CA", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 176, name: "Baal Red", hex: "0xFFB02018", metallic: false, typeId: 2, colourId: 12, accountId: 1),
  Paint(id: 177, name: "Basilicanum Grey", hex: "0xFF505A60", metallic: false, typeId: 2, colourId: 7, accountId: 1),
  Paint(id: 178, name: "Black Legion", hex: "0xFF434345", metallic: false, typeId: 2, colourId: 1, accountId: 1),
  Paint(id: 179, name: "Black Templar", hex: "0xFF1A1A1A", metallic: false, typeId: 2, colourId: 7, accountId: 1),
  Paint(id: 180, name: "Blood Angels Red", hex: "0xFFC02018", metallic: false, typeId: 2, colourId: 12, accountId: 1),
  Paint(id: 181, name: "Briar Queen Chill", hex: "0xFF91BDCA", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 182, name: "Celestium Blue", hex: "0xFF275996", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 183, name: "Creed Camo", hex: "0xFF485840", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 184, name: "Cygor Brown", hex: "0xFF604028", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 185, name: "Dark Angels Green", hex: "0xFF1A4020", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 186, name: "Doomfire Magenta", hex: "0xFFB02060", metallic: false, typeId: 2, colourId: 10, accountId: 1),
  Paint(id: 187, name: "Dreadful Visage", hex: "0xFFE4D3DF", metallic: false, typeId: 2, colourId: 7, accountId: 1),
  Paint(id: 188, name: "Flesh Tearers Red", hex: "0xFF880E0B", metallic: false, typeId: 2, colourId: 12, accountId: 1),
  Paint(id: 189, name: "Garaghak's Sewer", hex: "0xFF5D3418", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 190, name: "Gore-Grunta Fur", hex: "0xFF7A4828", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 191, name: "Gryph-Charger Grey", hex: "0xFF607080", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 192, name: "Gryph-Hound Orange", hex: "0xFFC05818", metallic: false, typeId: 2, colourId: 8, accountId: 1),
  Paint(id: 193, name: "Imperial Fist", hex: "0xFFe5c366", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 194, name: "Ironjawz Yellow", hex: "0xFFD0A020", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 195, name: "Iyanden Yellow", hex: "0xFFE8C000", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 196, name: "Kroxigor Scales", hex: "0xFF0099AA", metallic: false, typeId: 2, colourId: 4, accountId: 1),
  Paint(id: 197, name: "Leviadon Blue", hex: "0xFF1e3a8a", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 198, name: "Magmadroth Flame", hex: "0xFFD06018", metallic: false, typeId: 2, colourId: 8, accountId: 1),
  Paint(id: 199, name: "Magos Purple", hex: "0xFF784090", metallic: false, typeId: 2, colourId: 11, accountId: 1),
  Paint(id: 200, name: "Mantis Warriors Green", hex: "0xFF507840", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 201, name: "Militarum Green", hex: "0xFF4A6030", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 202, name: "Nazdreg Yellow", hex: "0xFFD0A018", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 203, name: "Orc Flesh", hex: "0xFF3E7C41", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 204, name: "Plaguebearer Flesh", hex: "0xFF909050", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 205, name: "Pylar Glacier", hex: "0xFF74C0EB", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 206, name: "Ratling Grime", hex: "0xFF8E8684", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 207, name: "Shyish Purple", hex: "0xFF503870", metallic: false, typeId: 2, colourId: 11, accountId: 1),
  Paint(id: 208, name: "Sigvald Burgundy", hex: "0xFF701840", metallic: false, typeId: 2, colourId: 10, accountId: 1),
  Paint(id: 209, name: "Skeleton Horde", hex: "0xFFC0A058", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 210, name: "Space Wolves Grey", hex: "0xFF7890A8", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 211, name: "Striking Scorpion Green", hex: "0xFF38B838", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 212, name: "Talassar Blue", hex: "0xFF2068B0", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 213, name: "Terradon Turquoise", hex: "0xFF309890", metallic: false, typeId: 2, colourId: 4, accountId: 1),
  Paint(id: 214, name: "Ultramarines Blue", hex: "0xFF294F86", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 215, name: "Volupus Pink", hex: "0xFFC03870", metallic: false, typeId: 2, colourId: 10, accountId: 1),
  Paint(id: 216, name: "Warp Lightning", hex: "0xFF38B030", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 217, name: "Wyldwood", hex: "0xFF503818", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 218, name: "Bad Moon Yellow", hex: "0xFFFFE100", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 219, name: "Sigvald Burgundy", hex: "0xFF701840", metallic: false, typeId: 2, colourId: 10, accountId: 1),
  Paint(id: 220, name: "Luxion Purple", hex: "0xFF431E75", metallic: false, typeId: 2, colourId: 11, accountId: 1),
  Paint(id: 221, name: "Leviathan Purple", hex: "0xFF431E75", metallic: false, typeId: 2, colourId: 11, accountId: 1),
  Paint(id: 222, name: "Frostheart", hex: "0xFF70A8C0", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 223, name: "Stormfield", hex: "0xFF00628F", metallic: false, typeId: 2, colourId: 2, accountId: 1),
  Paint(id: 224, name: "Akhelian Green", hex: "0xFF007B9B", metallic: false, typeId: 2, colourId: 4, accountId: 1),
  Paint(id: 225, name: "Aeldari Emerald", hex: "0xFF008973", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 226, name: "Karandras Green", hex: "0xFF2A6030", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 227, name: "Gutrippa Flesh", hex: "0xFF807850", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 228, name: "Hexwrath Flame", hex: "0xFF00A237", metallic: false, typeId: 2, colourId: 6, accountId: 1),
  Paint(id: 229, name: "Nighthaunt Gloom", hex: "0xFF78B0A8", metallic: false, typeId: 2, colourId: 4, accountId: 1),
  Paint(id: 230, name: "Aggaros Dunes", hex: "0xFFC8903A", metallic: false, typeId: 2, colourId: 15, accountId: 1),
  Paint(id: 231, name: "Snakebite Leather", hex: "0xFFA06830", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 232, name: "Guilliman Flesh", hex: "0xFFC87858", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 233, name: "Fyreslayer Flesh", hex: "0xFFBD7866", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 234, name: "Darkoath Flesh", hex: "0xFFB87050", metallic: false, typeId: 2, colourId: 3, accountId: 1),
  Paint(id: 235, name: "Hoeth Blue", hex: "0xFF4C7FB4", metallic: false, typeId: 3, colourId: 2, accountId: 1),
  Paint(id: 236, name: "Nurgling Green", hex: "0xFF849B63", metallic: false, typeId: 3, colourId: 6, accountId: 1),
  Paint(id: 237, name: "Dawnstone", hex: "0xFF70756E", metallic: false, typeId: 3, colourId: 7, accountId: 1),
  Paint(id: 238, name: "Hobgrot Hide", hex: "0xFF7A7828", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 239, name: "Gal Vorbak Red", hex: "0xFF5A1818", metallic: false, typeId: 1, colourId: 12, accountId: 1),
  Paint(id: 240, name: "Baral-Nar Burgundy", hex: "0xFF5A1A2A", metallic: false, typeId: 1, colourId: 11, accountId: 1),
  Paint(id: 241, name: "Phoenician Purple", hex: "0xFF5C1A5C", metallic: false, typeId: 1, colourId: 11, accountId: 1),
  Paint(id: 242, name: "Night Lords Blue", hex: "0xFF1A2850", metallic: false, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 243, name: "Lupercal Green", hex: "0xFF1A3828", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 244, name: "Death Korps Drab", hex: "0xFF3D4539", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 245, name: "Orruk Flesh", hex: "0xFF6B9850", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 246, name: "Nocturne Green", hex: "0xFF1A3320", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 247, name: "Wraithbone", hex: "0xFFeae6d7", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 248, name: "Morghast Bone", hex: "0xFFC0A973", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 249, name: "Thondia Brown", hex: "0xFF54302A", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 250, name: "Ionrach Skin", hex: "0xFF8BB0A0", metallic: false, typeId: 1, colourId: 6, accountId: 1),
  Paint(id: 251, name: "Catachan Flesh", hex: "0xFF442B25", metallic: false, typeId: 1, colourId: 3, accountId: 1),
  Paint(id: 252, name: "Grey Seer", hex: "0xFFD0D0C8", metallic: false, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 253, name: "Corvus Black", hex: "0xFF2A2A2A", metallic: false, typeId: 1, colourId: 1, accountId: 1),
  Paint(id: 254, name: "Grey Knights Steel", hex: "0xFF465863", metallic: true, typeId: 1, colourId: 2, accountId: 1),
  Paint(id: 255, name: "Iron Hands Steel", hex: "0xFF44423F", metallic: true, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 256, name: "Iron Warriors", hex: "0xFF292725", metallic: true, typeId: 1, colourId: 7, accountId: 1),
  Paint(id: 257, name: "Berserker Bloodshade", hex: "0xFF4f1c1c", metallic: false, typeId: 6, colourId: 12, accountId: 1),
  Paint(id: 258, name: "Targor Rageshade", hex: "0xFF602018", metallic: false, typeId: 6, colourId: 11, accountId: 1),
  Paint(id: 259, name: "Tyran Blue", hex: "0xFF1A48A0", metallic: false, typeId: 6, colourId: 2, accountId: 1),
  Paint(id: 260, name: "Kroak Green", hex: "0xFF7DBF92", metallic: false, typeId: 6, colourId: 6, accountId: 1),
  Paint(id: 261, name: "Poxwalker", hex: "0xFF54989C", metallic: false, typeId: 6, colourId: 4, accountId: 1),
  Paint(id: 262, name: "Mortarion Grime", hex: "0xFFAFA400", metallic: false, typeId: 6, colourId: 15, accountId: 1),
  Paint(id: 263, name: "Soulblight Grey", hex: "0xFFA6A1A5", metallic: false, typeId: 6, colourId: 7, accountId: 1),
  Paint(id: 264, name: "Phalanx Yellow", hex: "0xFFebee44", metallic: false, typeId: 4, colourId: 15, accountId: 1),
  Paint(id: 265, name: "Word Bearers Red", hex: "0xFF6B1818", metallic: false, typeId: 4, colourId: 12, accountId: 1),
  Paint(id: 266, name: "Kakophoni Purple", hex: "0xFF8869AE", metallic: false, typeId: 4, colourId: 11, accountId: 1),
  Paint(id: 267, name: "Sons of Horus Green", hex: "0xFF0f4b3c", metallic: false, typeId: 4, colourId: 4, accountId: 1),
  Paint(id: 268, name: "Vulkan Green", hex: "0xFF205830", metallic: false, typeId: 4, colourId: 6, accountId: 1),
  Paint(id: 269, name: "Knight-Questor Flesh", hex: "0xFFD8A070", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 270, name: "Bloodreaver Flesh", hex: "0xFFC86448", metallic: false, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 271, name: "Canoptek Alloy", hex: "0xFF8d6130", metallic: true, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 272, name: "Castellax Bronze", hex: "0xFF8C6820", metallic: true, typeId: 4, colourId: 3, accountId: 1),
  Paint(id: 273, name: "Mordant Earth", hex: "0xFF404040", metallic: false, typeId: 8, colourId: 1, accountId: 1),
  Paint(id: 274, name: "Stormshield", hex: "0xFF6B6B6B", metallic: false, typeId: 8, colourId: 9, accountId: 1),
  Paint(id: 275, name: "Ardcoat", hex: "0xFFF0F0F0", metallic: false, typeId: 8, colourId: 9, accountId: 1),
  Paint(id: 276, name: "Tesseract Glow", hex: "0xFF00ff04", metallic: false, typeId: 8, colourId: 6, accountId: 1),
  Paint(id: 277, name: "Lahmian Medium", hex: "0xFFE8E0D0", metallic: false, typeId: 8, colourId: 9, accountId: 1),
  Paint(id: 278, name: "Contrast Medium", hex: "0xFFFFFFFF", metallic: false, typeId: 8, colourId: 9, accountId: 1),
  Paint(id: 279, name: "Mechanicus Standard Grey", hex: "0xFF3D4B4E", metallic: false, typeId: 7, colourId: 7, accountId: 1),
  Paint(id: 280, name: "Zandri Dust", hex: "0xFF9E915C", metallic: false, typeId: 7, colourId: 3, accountId: 1),
  Paint(id: 281, name: "Mephiston Red", hex: "0xFF991115", metallic: false, typeId: 7, colourId: 12, accountId: 1),
  Paint(id: 282, name: "Death Guard Green", hex: "0xFF9C9171", metallic: false, typeId: 7, colourId: 6, accountId: 1),
  Paint(id: 283, name: "Grey Seer", hex: "0xFFD0D0C8", metallic: false, typeId: 7, colourId: 7, accountId: 1),
  Paint(id: 284, name: "Retributor Armour", hex: "0xFFCEAE65", metallic: true, typeId: 7, colourId: 15, accountId: 1),
  Paint(id: 285, name: "Leadbelcher", hex: "0xFF475659", metallic: true, typeId: 7, colourId: 7, accountId: 1),
  Paint(id: 286, name: "Macragge Blue", hex: "0xFF0D407F", metallic: false, typeId: 7, colourId: 2, accountId: 1),
  Paint(id: 287, name: "White Scar", hex: "0xFFFFFFFF", metallic: false, typeId: 7, colourId: 14, accountId: 1),
  Paint(id: 288, name: "Runelord Brass", hex: "0xFFBCAFA0", metallic: false, typeId: 7, colourId: 3, accountId: 1),
  Paint(id: 289, name: "Wraithbone", hex: "0xFFeae6d7", metallic: false, typeId: 7, colourId: 3, accountId: 1)
];