class ArmyType{
  final int id;
  final String name;

  ArmyType({required this.id, required this.name});
}

final List<ArmyType> armyTypeList = <ArmyType>[
  ArmyType(id: 1, name: "Space Marines"),
  ArmyType(id: 2, name: "Black Templars"),
  ArmyType(id: 3, name: "Blood Angels"),
  ArmyType(id: 4, name: "Dark Angels"),
  ArmyType(id: 5, name: "Deathwatch"),
  ArmyType(id: 6, name: "Grey Knights"),
  ArmyType(id: 7, name: "Space Wolves"),
  ArmyType(id: 8, name: "Adepta Sororitas"),
  ArmyType(id: 9, name: "Adeptus Custodes"),
  ArmyType(id: 10, name: "Adeptus Mechanicus"),
  ArmyType(id: 11, name: "Astra Militarum"),
  ArmyType(id: 12, name: "Chaos Space Marines"),
  ArmyType(id: 13, name: "Death Guard"),
  ArmyType(id: 14, name: "Thousand Sons"),
  ArmyType(id: 15, name: "World Eaters"),
  ArmyType(id: 16, name: "Chaos Daemons"),
  ArmyType(id: 17, name: "Aeldari"),
  ArmyType(id: 18, name: "Drukhari"),
  ArmyType(id: 19, name: "Tyranids"),
  ArmyType(id: 20, name: "Genestealer Cults"),
  ArmyType(id: 21, name: "Leagues of Votann"),
  ArmyType(id: 22, name: "Necrons"),
  ArmyType(id: 23, name: "Orks"),
  ArmyType(id: 24, name: "T'au Empire"),
  ArmyType(id: 25, name: "Cities of Sigmar"),
  ArmyType(id: 26, name: "Daughters of Khaine"),
  ArmyType(id: 27, name: "Fyreslayers"),
  ArmyType(id: 28, name: "Idoneth Deepkin"),
  ArmyType(id: 29, name: "Kharadron Overlords"),
  ArmyType(id: 30, name: "Lumineth Realm-lords"),
  ArmyType(id: 31, name: "Seraphon"),
  ArmyType(id: 32, name: "Stormcast Eternals"),
  ArmyType(id: 33, name: "Sylvaneth"),
  ArmyType(id: 34, name: "Blades of Khorne"),
  ArmyType(id: 35, name: "Disciples of Tzeentch"),
  ArmyType(id: 36, name: "Hedonites of Slaanesh"),
  ArmyType(id: 37, name: "Maggotkin of Nurgle"),
  ArmyType(id: 38, name: "Skaven"),
  ArmyType(id: 39, name: "Slaves to Darkness"),
  ArmyType(id: 40, name: "Flesh-eater Courts"),
  ArmyType(id: 41, name: "Nighthaunt"),
  ArmyType(id: 42, name: "Ossiarch Bonereapers"),
  ArmyType(id: 43, name: "Soulblight Gravelords"),
  ArmyType(id: 44, name: "Gloomspite Gitz"),
  ArmyType(id: 45, name: "Ogor Mawtribes"),
  ArmyType(id: 46, name: "Orruk Warclans"),
  ArmyType(id: 47, name: "Sons of Behemat"),
];